name: Run Single Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-one-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # adjust if needed

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run hrtk_0001.py
      run: |
        echo "Himanshu R Khatri" | python hrtk_0001.py
